services:
  reservation-system:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: reservation-system
    restart: always
    ports:
      - "8001:8001"
      - "5000:5000"
    volumes:
      - app-data:/app
      - ./.env:/app/.env
    environment:
      - TZ=Asia/Shanghai
      - PYTHONPATH=/app
    networks:
      - reservation-network

networks:
  reservation-network:
    driver: bridge

volumes:
  app-data:
    driver: local
